language: python
dist: xenial 
python:
  - "3.7"
# command to install dependencies
install:
  - conda create -q -n p4env python=$PYTHON_VER psi4 --only-deps -c psi4/label/dev
  - source activate p4env
  - pip install -r requirements.txt
# command to run tests
script:
  - pytest tests
